//
// Generated by CocoaPods-Keys
// on 05/07/2023
// For more information see https://github.com/orta/cocoapods-keys
//

#import <Foundation/NSString.h>

NS_ASSUME_NONNULL_BEGIN

@interface TDYCDBANKKeys : NSObject

@property (readonly) NSString *devAESKey;
@property (readonly) NSString *qaAESKey;
@property (readonly) NSString *uatAESKey;

@end

NS_ASSUME_NONNULL_END
